In [1]:
# Install required libraries
!pip install pandas openpyxl scikit-learn

# Import libraries
import pandas as pd
import numpy as np
import pickle

# Google Drive
from google.colab import drive, files

# Machine Learning models
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# Train-test evaluation
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("All libraries imported successfully!")

All libraries imported successfully!


In [2]:
# Connect Google Drive to Google Colab
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
train_file = '/content/drive/MyDrive/TRAIN_AI4I2020_PDM_DATASET.xlsx'
test_file = '/content/drive/MyDrive/TEST_AI4I2020_PDM_DATASET.xlsx'

In [5]:
# Read Training Excel file
train_df = pd.read_excel(train_file)

# Read Testing Excel file
test_df = pd.read_excel(test_file)

print("Training DataFrame created successfully!")
print("Testing DataFrame created successfully!")

print("\nTraining Dataset:")
display(train_df.head())

print("\nTesting Dataset:")
display(test_df.head())

Training DataFrame created successfully!
Testing DataFrame created successfully!

Training Dataset:


,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,298.1,308.6,1551,42.8,0,0
1,298.2,308.7,1408,46.3,3,0
2,298.1,308.5,1498,49.4,5,0
3,298.2,308.6,1433,39.5,7,0
4,298.2,308.7,1408,40.0,9,0



Testing Dataset:


,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,297.3,308.5,1710,27.7,138,0
1,297.3,308.6,1584,29.4,141,0
2,297.3,308.6,1446,50.1,144,0
3,297.4,308.7,1522,46.3,146,0
4,297.4,308.7,1382,49.9,151,0


In [6]:
X_train = train_df.iloc[:, 0:5]

y_train = train_df.iloc[:, 5]

X_test = test_df.iloc[:, 0:5]

y_test = test_df.iloc[:, 5]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

print("\nTraining Features (X_train):")
display(X_train.head())

print("\nTraining Labels (y_train):")
display(y_train.head())

print("\nTesting Features (X_test):")
display(X_test.head())

print("\nTesting Labels (y_test):")
display(y_test.head())

X_train shape: (7899, 5)
y_train shape: (7899,)
X_test shape: (1101, 5)
y_test shape: (1101,)

Training Features (X_train):


,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min]
0,298.1,308.6,1551,42.8,0
1,298.2,308.7,1408,46.3,3
2,298.1,308.5,1498,49.4,5
3,298.2,308.6,1433,39.5,7
4,298.2,308.7,1408,40.0,9



Training Labels (y_train):


,Machine failure
0,0
1,0
2,0
3,0
4,0



Testing Features (X_test):


,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min]
0,297.3,308.5,1710,27.7,138
1,297.3,308.6,1584,29.4,141
2,297.3,308.6,1446,50.1,144
3,297.4,308.7,1522,46.3,146
4,297.4,308.7,1382,49.9,151



Testing Labels (y_test):


,Machine failure
0,0
1,0
2,0
3,0
4,0


In [7]:
# Create Random Forest model
random_forest_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model using training data
random_forest_model.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!


In [8]:
# Create Decision Tree model
decision_tree_model = DecisionTreeClassifier(
    random_state=42
)

# Train the model
decision_tree_model.fit(X_train, y_train)

print("Decision Tree model trained successfully!")

Decision Tree model trained successfully!


In [9]:
# Create SVM model
svm_model = SVC(
    kernel='rbf',
    random_state=42
)

# Train the model
svm_model.fit(X_train, y_train)

print("SVM model trained successfully!")

SVM model trained successfully!


In [10]:
y_pred_rf = random_forest_model.predict(X_test)

print("Random Forest predictions generated successfully!")
print(y_pred_rf[:10])

Random Forest predictions generated successfully!
[0 0 0 0 0 0 0 0 0 0]


In [11]:
y_pred_dt = decision_tree_model.predict(X_test)

print("Decision Tree predictions generated successfully!")
print(y_pred_dt[:10])

Decision Tree predictions generated successfully!
[0 0 0 0 0 0 0 0 0 0]


In [12]:
y_pred_svm = svm_model.predict(X_test)

print("SVM predictions generated successfully!")
print(y_pred_svm[:10])

SVM predictions generated successfully!
[0 0 0 0 0 0 0 0 0 0]


In [14]:
def evaluate_model(model_name, y_test, y_pred):

    print("\n==========================================")
    print(model_name)
    print("==========================================")

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)

    print("\nConfusion Matrix:")
    print(cm)

    # Accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Precision
    precision = precision_score(
        y_test,
        y_pred,
        zero_division=0
    )

    # Recall
    recall = recall_score(
        y_test,
        y_pred,
        zero_division=0
    )

    # F1 Score
    f1 = f1_score(
        y_test,
        y_pred,
        zero_division=0
    )

    print("\nAccuracy :", accuracy)
    print("Precision:", precision)
    print("Recall   :", recall)
    print("F1-Score :", f1)

    return accuracy, precision, recall, f1

In [15]:
rf_results = evaluate_model(
    "Random Forest",
    y_test,
    y_pred_rf
)


Random Forest

Confusion Matrix:
[[1074    4]
 [   9   14]]

Accuracy : 0.9881925522252498
Precision: 0.7777777777777778
Recall   : 0.6086956521739131
F1-Score : 0.6829268292682927


In [16]:
dt_results = evaluate_model(
    "Decision Tree",
    y_test,
    y_pred_dt
)


Decision Tree

Confusion Matrix:
[[1071    7]
 [   8   15]]

Accuracy : 0.9863760217983651
Precision: 0.6818181818181818
Recall   : 0.6521739130434783
F1-Score : 0.6666666666666666


In [17]:
svm_results = evaluate_model(
    "SVM",
    y_test,
    y_pred_svm
)


SVM

Confusion Matrix:
[[1077    1]
 [  23    0]]

Accuracy : 0.9782016348773842
Precision: 0.0
Recall   : 0.0
F1-Score : 0.0


In [21]:
with open("random_forest_model.pkl", "wb") as file:
    pickle.dump(random_forest_model, file)

print("Random Forest model saved as random_forest_model.pkl")

Random Forest model saved as random_forest_model.pkl


In [19]:
with open("decision_tree_model.pkl", "wb") as file:
    pickle.dump(decision_tree_model, file)

print("Decision Tree model saved as decision_tree_model.pkl")

Decision Tree model saved as decision_tree_model.pkl


In [20]:
with open("svm_model.pkl", "wb") as file:
    pickle.dump(svm_model, file)

print("SVM model saved as svm_model.pkl")

SVM model saved as svm_model.pkl


In [22]:
from google.colab import files

files.download("random_forest_model.pkl")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [23]:
files.download("decision_tree_model.pkl")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [24]:
files.download("svm_model.pkl")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>